name: 部署博客到 GitHub Pages

on:
  # 当推送到 main 分支时触发
  push:
    branches: ["main"]

  # 允许从 GitHub UI 手动触发工作流
  workflow_dispatch:

# 设置 GitHub Token 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署到 GitHub Pages
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建博客的任务
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36  # 如果你使用 mdBook，可以指定版本
    steps:
      # 检出代码库
      - uses: actions/checkout@v4

      # 安装 mdBook（如果你使用的是 mdBook 生成博客）
      - name: 安装 mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook

      # 配置 GitHub Pages
      - name: 配置 Pages
        id: pages
        uses: actions/configure-pages@v5

      # 使用 mdBook 构建博客（如果你使用的是其他生成器，请根据需要调整）
      - name: 使用 mdBook 构建博客
        run: mdbook build  # 如果是 Jekyll、Hugo 等，请改为相应的构建命令

      # 上传构建好的博客文件
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book  # mdBook 会把生成的内容放在 `./book` 文件夹，其他生成器可能是其他文件夹

  # 部署博客的任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
